module.exports = {
  mySidebar: [
    "index",
    {
      type: "category",
      label: "Overview",
      collapsed: false,
      link: { type: "doc", id: "overview" },
      items: [
        "getting-started",
        "release-notes",
        "using-opcon-deploy",
        "user-interface",
      ],
    },
    "installation",
    "schedules",
    "packages",
    {
      type: "category",
      label: "Scripts",
      collapsed: true,
      link: { type: "doc", id: "scripts-overview" },
      items: [
        "script-management",
        "scripts",
      ],
    },
    {
      type: "category",
      label: "Deployments",
      collapsed: true,
      link: { type: "doc", id: "deployments/deployments-overview" },
      items: [
        "deployments/deployments",
        "deployments/deployments-browse",
        "deployments/transformation-rules-tree",
        "deploy-sap-jobs",
      ],
    },
    {
      type: "category",
      label: "Transformations",
      collapsed: true,
      link: { type: "doc", id: "transformations/transformations-overview" },
      items: [
        "transformations/transformation-rules",
        "transformations/transformation-tag-definitions",
        "transformations/transformation-tag-examples",
        "transformations/transformations-special-definitions",
      ],
    },
    {
      type: "category",
      label: "Administration",
      collapsed: true,
      link: { type: "doc", id: "administration/administration-overview" },
      items: [
        "administration/users",
        "administration/servers",
        "administration/audits",
        "administration/settings",
      ],
    },
    {
      type: "category",
      label: "Batch Processing",
      collapsed: true,
      link: { type: "doc", id: "batch-processing-overview" },
      items: [
        "batch-processing",
        "scheduled-batch-deployment",
        "batch-deployment-implementation",
        "batch-file-integration",
        "batch-devops-integration",
        "batch-diagram-processing",
      ],
    },
    {
      type: "category",
      label: "Diagrams and Archiving",
      collapsed: true,
      link: { type: "doc", id: "diagrams-archiving-overview" },
      items: [
        "package-and-schedule-diagram",
        "database-archiving",
      ],
    },
  ],
}
